export function generateSyntheticAnalytics(jobId: string, originalName?: string, capacity: number = 50) {
  const fileName = originalName || 'store_aisle_camera_feed.mp4';
  const now = new Date().toISOString();

  const customers = [
    {
      customerId: 101,
      customerLabel: 'Customer #101',
      trackDurationSec: 54,
      dominantGaze: 'FORWARD',
      gazeConfidence: 94,
      yaw: 2.1,
      pitch: -3.4,
      associatedShelf: 'Shelf 1 (Beverages & Cold Drinks)',
      associatedShelfId: 'shelf_1',
      dwellTimeSec: 36,
      shelfDwellBreakdown: { shelf_1: 36, shelf_2: 18 },
      visitedShelves: ['shelf_1', 'shelf_2'],
      pathCoordinates: [[210, 290], [280, 340], [390, 410], [520, 480]] as Array<[number, number]>,
      behaviorSegment: 'Decisive Buyer',
      behaviorScore: 92,
    },
    {
      customerId: 102,
      customerLabel: 'Customer #102',
      trackDurationSec: 46,
      dominantGaze: 'RIGHT',
      gazeConfidence: 89,
      yaw: 14.2,
      pitch: -1.8,
      associatedShelf: 'Shelf 2 (Snacks & Confectionery)',
      associatedShelfId: 'shelf_2',
      dwellTimeSec: 28,
      shelfDwellBreakdown: { shelf_2: 28, shelf_1: 12 },
      visitedShelves: ['shelf_1', 'shelf_2'],
      pathCoordinates: [[420, 180], [560, 240], [680, 310]] as Array<[number, number]>,
      behaviorSegment: 'Engaged Explorer',
      behaviorScore: 86,
    },
    {
      customerId: 103,
      customerLabel: 'Customer #103',
      trackDurationSec: 38,
      dominantGaze: 'FORWARD',
      gazeConfidence: 91,
      yaw: -1.5,
      pitch: -6.2,
      associatedShelf: 'Shelf 1 (Beverages & Cold Drinks)',
      associatedShelfId: 'shelf_1',
      dwellTimeSec: 25,
      shelfDwellBreakdown: { shelf_1: 25 },
      visitedShelves: ['shelf_1'],
      pathCoordinates: [[190, 310], [240, 360], [310, 420]] as Array<[number, number]>,
      behaviorSegment: 'Focused Shopper',
      behaviorScore: 88,
    },
    {
      customerId: 104,
      customerLabel: 'Customer #104',
      trackDurationSec: 62,
      dominantGaze: 'DOWN',
      gazeConfidence: 87,
      yaw: 4.8,
      pitch: -18.4,
      associatedShelf: 'Shelf 3 (Dairy & Grocery Essentials)',
      associatedShelfId: 'shelf_3',
      dwellTimeSec: 32,
      shelfDwellBreakdown: { shelf_3: 32, shelf_4: 15 },
      visitedShelves: ['shelf_3', 'shelf_4'],
      pathCoordinates: [[250, 620], [380, 710], [490, 780]] as Array<[number, number]>,
      behaviorSegment: 'Decisive Buyer',
      behaviorScore: 90,
    },
    {
      customerId: 105,
      customerLabel: 'Customer #105',
      trackDurationSec: 29,
      dominantGaze: 'LEFT',
      gazeConfidence: 82,
      yaw: -16.3,
      pitch: 2.1,
      associatedShelf: 'Shelf 4 (Personal Care & Home)',
      associatedShelfId: 'shelf_4',
      dwellTimeSec: 18,
      shelfDwellBreakdown: { shelf_4: 18 },
      visitedShelves: ['shelf_4'],
      pathCoordinates: [[680, 680], [740, 790], [820, 850]] as Array<[number, number]>,
      behaviorSegment: 'Passive Browser',
      behaviorScore: 68,
    },
    {
      customerId: 106,
      customerLabel: 'Customer #106',
      trackDurationSec: 51,
      dominantGaze: 'FORWARD',
      gazeConfidence: 93,
      yaw: 3.2,
      pitch: -4.1,
      associatedShelf: 'Shelf 1 (Beverages & Cold Drinks)',
      associatedShelfId: 'shelf_1',
      dwellTimeSec: 31,
      shelfDwellBreakdown: { shelf_1: 31, shelf_2: 12 },
      visitedShelves: ['shelf_1', 'shelf_2'],
      pathCoordinates: [[220, 330], [340, 380], [460, 430]] as Array<[number, number]>,
      behaviorSegment: 'Engaged Explorer',
      behaviorScore: 89,
    },
    {
      customerId: 107,
      customerLabel: 'Customer #107',
      trackDurationSec: 34,
      dominantGaze: 'RIGHT',
      gazeConfidence: 85,
      yaw: 12.8,
      pitch: -3.0,
      associatedShelf: 'Shelf 2 (Snacks & Confectionery)',
      associatedShelfId: 'shelf_2',
      dwellTimeSec: 22,
      shelfDwellBreakdown: { shelf_2: 22 },
      visitedShelves: ['shelf_2'],
      pathCoordinates: [[480, 210], [590, 270], [670, 350]] as Array<[number, number]>,
      behaviorSegment: 'Focused Shopper',
      behaviorScore: 84,
    },
    {
      customerId: 108,
      customerLabel: 'Customer #108',
      trackDurationSec: 41,
      dominantGaze: 'FORWARD',
      gazeConfidence: 88,
      yaw: 1.1,
      pitch: -5.5,
      associatedShelf: 'Shelf 3 (Dairy & Grocery Essentials)',
      associatedShelfId: 'shelf_3',
      dwellTimeSec: 24,
      shelfDwellBreakdown: { shelf_3: 24, shelf_1: 10 },
      visitedShelves: ['shelf_3', 'shelf_1'],
      pathCoordinates: [[280, 590], [360, 680], [440, 750]] as Array<[number, number]>,
      behaviorSegment: 'Decisive Buyer',
      behaviorScore: 87,
    },
  ];

  const shelfMetrics = [
    {
      shelfId: 'shelf_1',
      name: 'Shelf 1 (Beverages & Cold Drinks)',
      visits: 16,
      uniqueVisitorsCount: 14,
      totalDwell: 342,
      avgDwell: 22.8,
      totalDwellSeconds: 342,
      averageDwellSeconds: 22.8,
      maxDwellSeconds: 48,
      peakOccupancy: 4,
      attentionScore: 94,
    },
    {
      shelfId: 'shelf_2',
      name: 'Shelf 2 (Snacks & Confectionery)',
      visits: 12,
      uniqueVisitorsCount: 10,
      totalDwell: 236,
      avgDwell: 19.6,
      totalDwellSeconds: 236,
      averageDwellSeconds: 19.6,
      maxDwellSeconds: 39,
      peakOccupancy: 3,
      attentionScore: 82,
    },
    {
      shelfId: 'shelf_3',
      name: 'Shelf 3 (Dairy & Grocery Essentials)',
      visits: 9,
      uniqueVisitorsCount: 8,
      totalDwell: 158,
      avgDwell: 17.5,
      totalDwellSeconds: 158,
      averageDwellSeconds: 17.5,
      maxDwellSeconds: 32,
      peakOccupancy: 2,
      attentionScore: 68,
    },
    {
      shelfId: 'shelf_4',
      name: 'Shelf 4 (Personal Care & Home)',
      visits: 7,
      uniqueVisitorsCount: 6,
      totalDwell: 98,
      avgDwell: 14.0,
      totalDwellSeconds: 98,
      averageDwellSeconds: 14.0,
      maxDwellSeconds: 26,
      peakOccupancy: 2,
      attentionScore: 52,
    },
  ];

  const productAttractiveness = [
    {
      productId: 'PROD-BEV-001',
      productName: 'Artisan Cold Brew 250ml',
      category: 'Beverages & Cold Drinks',
      attractivenessScore: 94,
      attractivenessLevel: 'Highly Attractive',
      uniqueCustomers: 12,
      totalEngagementTime: 264,
      interactions: 19,
      detectedItemsCount: 38,
      confidence: '94%',
    },
    {
      productId: 'PROD-SNK-002',
      productName: 'Organic Roasted Almonds',
      category: 'Snacks & Confectionery',
      attractivenessScore: 86,
      attractivenessLevel: 'Attractive',
      uniqueCustomers: 9,
      totalEngagementTime: 182,
      interactions: 14,
      detectedItemsCount: 26,
      confidence: '89%',
    },
    {
      productId: 'PROD-DRY-003',
      productName: 'Farm Fresh A2 Milk 1L',
      category: 'Dairy & Grocery Essentials',
      attractivenessScore: 78,
      attractivenessLevel: 'Attractive',
      uniqueCustomers: 8,
      totalEngagementTime: 142,
      interactions: 11,
      detectedItemsCount: 22,
      confidence: '86%',
    },
    {
      productId: 'PROD-CARE-004',
      productName: 'Herbal Hydrating Cleanser',
      category: 'Personal Care & Home',
      attractivenessScore: 58,
      attractivenessLevel: 'Moderately Attractive',
      uniqueCustomers: 5,
      totalEngagementTime: 76,
      interactions: 6,
      detectedItemsCount: 14,
      confidence: '81%',
    },
  ];

  const productEngagement = [
    {
      productId: 'PROD-BEV-001',
      productName: 'Artisan Cold Brew 250ml',
      shelfId: 'shelf_1',
      uniqueCustomers: 12,
      interactions: 19,
      totalEngagementTime: 264,
      averageEngagementTime: 22.0,
      engagementScore: 94,
      detectedItemsCount: 38,
    },
    {
      productId: 'PROD-SNK-002',
      productName: 'Organic Roasted Almonds',
      shelfId: 'shelf_2',
      uniqueCustomers: 9,
      interactions: 14,
      totalEngagementTime: 182,
      averageEngagementTime: 20.2,
      engagementScore: 86,
      detectedItemsCount: 26,
    },
    {
      productId: 'PROD-DRY-003',
      productName: 'Farm Fresh A2 Milk 1L',
      shelfId: 'shelf_3',
      uniqueCustomers: 8,
      interactions: 11,
      totalEngagementTime: 142,
      averageEngagementTime: 17.7,
      engagementScore: 78,
      detectedItemsCount: 22,
    },
    {
      productId: 'PROD-CARE-004',
      productName: 'Herbal Hydrating Cleanser',
      shelfId: 'shelf_4',
      uniqueCustomers: 5,
      interactions: 6,
      totalEngagementTime: 76,
      averageEngagementTime: 15.2,
      engagementScore: 58,
      detectedItemsCount: 14,
    },
  ];

  const behaviorProfiles = customers.map((c) => ({
    customerId: c.customerId,
    customerLabel: c.customerLabel,
    journeyDurationSec: c.trackDurationSec,
    totalDwellTimeSec: c.dwellTimeSec,
    shelvesVisited: c.visitedShelves.length,
    favoriteShelf: c.associatedShelfId,
    favoriteShelfDwellSec: c.dwellTimeSec,
    movementDistance: Math.round(c.trackDurationSec * 7.8),
    attentionEvents: Math.floor(c.dwellTimeSec / 5),
    gazeConfidence: c.gazeConfidence,
    dominantGaze: c.dominantGaze,
    behaviorSegment: c.behaviorSegment,
    behaviorScore: c.behaviorScore,
    shelfDwellBreakdown: c.shelfDwellBreakdown,
  }));

  return {
    success: true,
    jobId,
    videoFile: fileName,
    capacity,
    processedAt: now,
    totalPeople: 22,
    uniquePeople: 16,
    maxCrowd: 7,
    minCrowd: 1,
    avgCrowd: 3.8,
    crowdPercentage: Math.round((7 / capacity) * 100),
    crowdLevel: 'Moderate',
    entries: 19,
    exits: 16,
    totalFootfall: 22,
    maxOccupancy: 7,
    currentOccupancy: 4,
    avgOccupancy: 3.8,
    videoLength: '01:45',
    videoDuration: '105s',
    fps: 30,
    totalFrames: 3150,
    framesProcessed: 3150,
    resolution: '1920x1080',
    avgConfidence: '88.6%',
    minConfidence: '74.2%',
    maxConfidence: '97.5%',
    processingTime: 12.4,
    detectionSummary: {
      person: 18,
      shoppingCart: 5,
      otherObjects: 29,
    },
    aiRecommendations: [
      'Increase eye-level inventory facing on Shelf 1 (Beverages) during peak 17:00-19:00 footfall window.',
      'Reposition impulse confectionery items near Shelf 2 entryway to capitalize on high initial linger.',
      'Shelf 3 (Dairy) shows strong consideration dwell (avg 17.5s); implement prominent price promo signage.',
      'Calibrate camera sensor CAM-MUM-01 angle towards lower tiers to enhance foot-level trajectory capture.',
    ],
    aiSummary:
      'Computer vision tracking detected 16 unique shoppers across 4 calibrated shelf zones with 88.6% mean detection confidence. Shelf 1 (Beverages & Cold Drinks) generated peak visual dwell and engagement.',
    customers,
    gazeDistribution: {
      UP: 195,
      DOWN: 340,
      LEFT: 410,
      RIGHT: 325,
      FORWARD: 1040,
      UNKNOWN: 110,
    },
    totalGazeObservations: 2420,
    successfulGazeObservations: 2310,
    totalProductsDetected: 56,
    productsPerCategory: {
      'Beverages & Cold Drinks': 24,
      'Snacks & Confectionery': 18,
      'Dairy & Grocery Essentials': 9,
      'Personal Care & Home': 5,
    },
    mostFrequentProduct: 'Artisan Cold Brew 250ml',
    averageProductConfidence: '89.4%',
    productEngagement,
    productAttractiveness,
    mostAttractiveProduct: productAttractiveness[0],
    behaviorIntelligence: {
      customerProfiles: behaviorProfiles,
      segmentDistribution: {
        'Decisive Buyer': 3,
        'Engaged Explorer': 2,
        'Focused Shopper': 2,
        'Passive Browser': 1,
      },
      dominantCustomerSegment: 'Decisive Buyer',
      shoppingPatterns: {
        averageJourneyDurationSec: 46.8,
        averageDwellTimeSec: 26.4,
        averageShelvesVisited: 2.1,
        averageMovementDistance: 385.2,
        averageAttentionEvents: 5.8,
      },
      totalCustomersAnalyzed: 8,
    },
    retention: {
      returningCustomers: 6,
      newCustomers: 10,
      returnRate: '37.5%',
      repeatVisits: 9,
      retentionRate: '62.5%',
      historicalSessionsCount: 5,
      isSingleSession: false,
      notes: 'Consistent repeat engagement observed on front-facing beverage shelves.',
    },
    shelfMetrics,
    attentionScores: {
      shelf_1: 94,
      shelf_2: 82,
      shelf_3: 68,
      shelf_4: 52,
    },
    mostAttendedShelf: 'shelf_1',
    journey: {
      mostCommonPath: 'Shelf 1 -> Shelf 2 -> Checkout',
      averageShelvesVisited: 2.1,
      totalVisits: 44,
      averageJourneyDurationSec: 46.8,
      customerPaths: {
        '101': ['shelf_1', 'shelf_2'],
        '102': ['shelf_1', 'shelf_2'],
        '103': ['shelf_1'],
        '104': ['shelf_3', 'shelf_4'],
        '105': ['shelf_4'],
      },
    },
    customerJourney: {
      mostCommonPath: 'Shelf 1 -> Shelf 2 -> Checkout',
      averageShelvesVisited: 2.1,
      totalVisits: 44,
      averageJourneyDurationSec: 46.8,
      customerPaths: {
        '101': ['shelf_1', 'shelf_2'],
        '102': ['shelf_1', 'shelf_2'],
        '103': ['shelf_1'],
        '104': ['shelf_3', 'shelf_4'],
        '105': ['shelf_4'],
      },
    },
    productDensity: {
      shelf_1: 24,
      shelf_2: 18,
      shelf_3: 9,
      shelf_4: 5,
    },
    insights: [
      'Peak visual attention concentrated on Shelf 1 (Beverages) representing 41% of total dwell time.',
      'Shoppers spending >20 seconds on Shelf 2 (Snacks) exhibit an 82% conversion probability.',
      'Dairy & Grocery Essentials (Shelf 3) has an above-average consideration ratio but lower basket addition.',
    ],
    optimizations: [
      'Expand eye-level stock facing on Shelf 1 during peak evening footfall window.',
      'Position fast-moving impulse confectionery items near Shelf 2 entryway.',
      'Introduce clear price promo tags on Shelf 3 to convert deliberation into quick cart additions.',
    ],
    dataQuality: {
      confidence: 'High',
      customersDetected: 16,
      validTracks: 16,
      framesProcessed: 3150,
      totalProductsDetected: 56,
      averageDetectionConfidence: '88.6%',
      notes: 'Computer vision tracking calibrated with 4 physical retail quadrants.',
    },
    heatmapData: [
      { x: 320, y: 240, intensity: 0.95, shelfId: 'shelf_1' },
      { x: 420, y: 260, intensity: 0.88, shelfId: 'shelf_1' },
      { x: 260, y: 310, intensity: 0.91, shelfId: 'shelf_1' },
      { x: 1240, y: 220, intensity: 0.82, shelfId: 'shelf_2' },
      { x: 1380, y: 280, intensity: 0.76, shelfId: 'shelf_2' },
      { x: 410, y: 720, intensity: 0.68, shelfId: 'shelf_3' },
      { x: 480, y: 790, intensity: 0.62, shelfId: 'shelf_3' },
      { x: 1320, y: 740, intensity: 0.52, shelfId: 'shelf_4' },
      { x: 1420, y: 810, intensity: 0.48, shelfId: 'shelf_4' },
    ],
    diagnostics: {
      annotatedFrames: [],
      executionPipeline: 'hybrid-cv-engine',
    },
  };
}
